### ISSUE TITLE
cant attack

### ISSUE THREAD

**Issue by Pinarello45** [TheMulhima/HollowKnight.DebugMod#34]
now that i activated the mod i can attack any more and even after i deleted the mod my save is now ruined

**Comment by DwarfWoot** [comment]
Changes made by Debug are saved to the file.
You can restore a Backup of your save if haven't saved more than a couple of times on that file (by locating your Saves Directory, and then changing user#.dat.bak# to user#.dat (where the first # is the save file number, and the second # is the backup number).
Alternatively, you can just do the opposite of whatever you did to not attack anymore. I assume that you set your damage to 0, so you could just use the "reset nail" option in the Binds panel.
